# Blueprint for deploying a full-stack Flask (backend) + React (frontend) app on Render
services:
  # Flask backend
  - type: web
    name: backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python server3.py
    healthCheckPath: /
    autoDeploy: true

  # React frontend
  - type: web
    name: frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: build
    autoDeploy: true
